apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1
  version: "1.30"

iam:
  withOIDC: true  # Enables IAM roles for service accounts (needed for monitoring & add-ons)

vpc:
  cidr: 10.0.0.0/16

managedNodeGroups:
  - name: ng-general
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    ssh:
      allow: true
      publicKeyName: ekscluster
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        cloudWatch: true
