apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.student.service.name }}
                port:
                  number: {{ .Values.student.service.port }}
          - path: /rating
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rating.service.name }}
                port:
                  number: {{ .Values.rating.service.port }}
