apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-role-binding
  namespace: staging
subjects:
  - kind: User
    name: staging-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
