apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rating-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AnithaAnnem/java-minikube.git'
    targetRevision: HEAD
    path: helm/rating-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
