apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AnithaAnnem/java-minikube.git'   # your repo
    targetRevision: HEAD
    path: helm/student-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
