apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    run: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rating-service
  template:
    metadata:
      labels:
        run: rating-service
    spec:
      containers:
      - name: rating-service
        image: anithaannem/rating-service:1.0
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_HOST
          value: rating-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: ratingdb
        - name: DB_USER
          value: ratinguser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rating-db-secret
              key: db-password
