apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    run: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rating-service
  template:
    metadata:
      labels:
        run: rating-service
    spec:
      containers:
      - name: rating-service
        image: anithaannem/rating-service:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: DB_HOST
          value: rating-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: ratingdb
        - name: DB_USER
          value: ratinguser
        - name: DB_PASSWORD
          value: ratingpass
        volumeMounts:
        - name: rating-pv
          mountPath: /var/lib/rating-data
      volumes:
      - name: rating-pv
        persistentVolumeClaim:
          claimName: rating-mysql-pvc
