apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  labels:
    run: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: student-service
  template:
    metadata:
      labels:
        run: student-service
    spec:
      containers:
      - name: student-service
        image: anithaannem/student-service:1.0 
        ports:
        - containerPort: 7000
          protocol: TCP
        env:
        - name: DB_HOST
          value: student-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: studentdb
        - name: DB_USER
          value: studentuser
        - name: DB_PASSWORD
          value: studentpass
        volumeMounts:
        - name: student-pv
          mountPath: /var/lib/student-data
      volumes:
      - name: student-pv
        persistentVolumeClaim:
          claimName: student-mysql-pvc
