apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  type: NodePort
  selector:
    run: rating-service
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002
