kind: Service
apiVersion: v1
metadata:
  name: rating-service
spec:
  type: NodePort         # change here
  selector:
    run: rating-service
  ports:
    - name: port1
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002    # assign a free port
