apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  type: ClusterIP
  selector:
    app: rating-chart
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
