apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: student-mysql
spec:
  serviceName: "student-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: student-mysql
  template:
    metadata:
      labels:
        app: student-mysql
    spec:
      containers:
      - name: student-mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: studentdb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: db-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2-csi
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: student-mysql
spec:
  selector:
    app: student-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None   
